#cloud-config 

# Disable selinux and firewalld

runcmd:
  - setenforce 0
  - sed -i 's/enforcing/disabled/g' /etc/selinux/config
  - systemctl stop firewalld
  - systemctl disable firewalld 
  - cd /opt
  - yum install git -y
  - git clone https://github.com/4linux/files-oci-4linux.git


 