#cloud-config

  
# Packages essentials
packages:
  - vim 
  - net-tools
  - build-essential
  - docker.io


# Docker full installation 
packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - vagrant
  - gnupg-agent
  - software-properties-common

# Create the docker group
groups:
  - docker

# Add default auto created user to docker group
system_info:
  default_user:
    groups: [docker]

#  Up dockerfile for container ubuntu-ssh
runcmd:
  - systemctl start docker
  - systemctl enable docker
  - cd /opt
  - git clone https://github.com/4linux/files-oci-4linux.git
  - docker image build -t ubuntu-ssh /opt/files-oci-4linux/ubuntu/docker-vagrant
  - docker network create --driver bridge --subnet 172.18.0.0/16 dexterlan 
